### ISSUE TITLE
体验地址

### ISSUE THREAD

**Issue by wuyouzhuguli** [yuuki80code/cooky-go#1]
您好，请问有体验地址吗？

 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by YuukiLa** [comment]
@wuyouzhuguli


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by YuukiLa** [comment]
> 您好，请问有体验地址吗？
> 
> :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

已加，管理员的也给了求别改东西~
